print("Welcome to the calculator program!")
print("This program will add, subtract, multiply, and divide two numbers respectively.")
print()
a = input("Enter an integer:")
b = input("Enter another integer:")
print("The sum of both integers is", int(a) + int(b))
print()
c = input("Enter any number:")
d = input("Enter another number:")
print("The difference of both numbers is", float(c) - float(d))
print()
e = input("Enter any number:")
f = input("Enter another number:")
print("The product of both numbers is", float(e) * float(f))
print()
g = input("Enter any number:")
h = input("Enter another number:")
print("The quotient of both numbers is", float(g) / float(h))
